/// Build script to generate test positions at compile time
/// This ensures test positions are always in sync with the source code
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=src/");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("test_positions_generated.rs");

    let positions = generate_positions();
    fs::write(&dest_path, positions).unwrap();
}

fn generate_positions() -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated test positions by build.rs\n");
    output.push_str("// DO NOT EDIT - this file is automatically generated\n\n");

    // Find positions in main.rs
    if let Ok(main_positions) = find_positions_in_file("src/main.rs") {
        output.push_str("pub mod main_rs {\n");
        output.push_str("    pub const FILE: &str = \"src/main.rs\";\n");

        if let Some(pos) = main_positions.find_function("main") {
            output.push_str(&format!(
                "    pub const MAIN_FUNCTION: (u32, u32) = ({}, {});\n",
                pos.0, pos.1
            ));
        }

        if let Some(pos) = main_positions.find_text("RustAnalyzerMCP") {
            output.push_str(&format!(
                "    pub const RUST_ANALYZER_IMPORT: (u32, u32) = ({}, {});\n",
                pos.0, pos.1
            ));
        }

        if let Some(pos) = main_positions.find_text("Args::parse()") {
            output.push_str(&format!(
                "    pub const ARGS_PARSE: (u32, u32) = ({}, {});\n",
                pos.0, pos.1
            ));
        }

        output.push_str("}\n\n");
    }

    // Find positions in lsp_client.rs
    if let Ok(lsp_positions) = find_positions_in_file("src/lsp_client.rs") {
        output.push_str("pub mod lsp_client_rs {\n");
        output.push_str("    pub const FILE: &str = \"src/lsp_client.rs\";\n");

        if let Some(pos) = lsp_positions.find_struct("LspClient") {
            output.push_str(&format!(
                "    pub const LSP_CLIENT_STRUCT: (u32, u32) = ({}, {});\n",
                pos.0, pos.1
            ));
        }

        if let Some(pos) = lsp_positions.find_function("new") {
            output.push_str(&format!(
                "    pub const NEW_METHOD: (u32, u32) = ({}, {});\n",
                pos.0, pos.1
            ));
        }

        if let Some(pos) = lsp_positions.find_function("hover") {
            output.push_str(&format!(
                "    pub const HOVER_METHOD: (u32, u32) = ({}, {});\n",
                pos.0, pos.1
            ));
        }

        output.push_str("}\n\n");
    }

    // Find positions in models.rs
    if let Ok(models_positions) = find_positions_in_file("src/models.rs") {
        output.push_str("pub mod models_rs {\n");
        output.push_str("    pub const FILE: &str = \"src/models.rs\";\n");

        if let Some(pos) = models_positions.find_struct("HoverRequest") {
            output.push_str(&format!(
                "    pub const HOVER_REQUEST_STRUCT: (u32, u32) = ({}, {});\n",
                pos.0, pos.1
            ));
        }

        if let Some(pos) = models_positions.find_struct("CompletionRequest") {
            output.push_str(&format!(
                "    pub const COMPLETION_REQUEST: (u32, u32) = ({}, {});\n",
                pos.0, pos.1
            ));
        }

        if let Some(pos) = models_positions.find_field("file_path") {
            output.push_str(&format!(
                "    pub const FILE_PATH_FIELD: (u32, u32) = ({}, {});\n",
                pos.0, pos.1
            ));
        }

        output.push_str("}\n\n");
    }

    // Find positions in errors.rs
    if let Ok(errors_positions) = find_positions_in_file("src/errors.rs") {
        output.push_str("pub mod errors_rs {\n");
        output.push_str("    pub const FILE: &str = \"src/errors.rs\";\n");

        if let Some(pos) = errors_positions.find_enum("LspError") {
            output.push_str(&format!(
                "    pub const LSP_ERROR_ENUM: (u32, u32) = ({}, {});\n",
                pos.0, pos.1
            ));
        }

        if let Some(pos) = errors_positions.find_text("RustAnalyzerNotFound") {
            output.push_str(&format!(
                "    pub const RUST_ANALYZER_NOT_FOUND: (u32, u32) = ({}, {});\n",
                pos.0, pos.1
            ));
        }

        if let Some(pos) = errors_positions.find_text("TimeoutError") {
            output.push_str(&format!(
                "    pub const TIMEOUT_ERROR: (u32, u32) = ({}, {});\n",
                pos.0, pos.1
            ));
        }

        output.push_str("}\n\n");
    }

    // Add invalid files module
    output.push_str("pub mod invalid_files {\n");
    output.push_str("    pub const NON_EXISTENT: &str = \"src/does_not_exist.rs\";\n");
    output.push_str("    pub const PATH_TRAVERSAL: &str = \"../../../etc/passwd\";\n");
    output.push_str("    pub const EMPTY_PATH: &str = \"\";\n");
    output.push_str("}\n");

    output
}

struct FilePositions {
    content: String,
}

impl FilePositions {
    fn find_text(&self, text: &str) -> Option<(u32, u32)> {
        for (line_num, line) in self.content.lines().enumerate() {
            if let Some(col) = line.find(text) {
                return Some((line_num as u32, col as u32));
            }
        }
        None
    }

    fn find_struct(&self, name: &str) -> Option<(u32, u32)> {
        self.find_pattern(&format!("struct {}", name))
            .or_else(|| self.find_pattern(&format!("pub struct {}", name)))
    }

    fn find_enum(&self, name: &str) -> Option<(u32, u32)> {
        self.find_pattern(&format!("enum {}", name))
            .or_else(|| self.find_pattern(&format!("pub enum {}", name)))
    }

    fn find_function(&self, name: &str) -> Option<(u32, u32)> {
        // Try different function patterns
        let patterns = vec![
            format!("pub async fn {}", name),
            format!("pub fn {}", name),
            format!("async fn {}", name),
            format!("fn {}", name),
        ];

        for pattern in patterns {
            if let Some(pos) = self.find_pattern(&pattern) {
                return Some(pos);
            }
        }
        None
    }

    fn find_field(&self, name: &str) -> Option<(u32, u32)> {
        // Look for field definitions
        for (line_num, line) in self.content.lines().enumerate() {
            let trimmed = line.trim_start();
            if trimmed.starts_with(&format!("pub {}:", name))
                || trimmed.starts_with(&format!("{}:", name))
            {
                if let Some(col) = line.find(name) {
                    return Some((line_num as u32, col as u32));
                }
            }
        }
        None
    }

    fn find_pattern(&self, pattern: &str) -> Option<(u32, u32)> {
        for (line_num, line) in self.content.lines().enumerate() {
            if line.contains(pattern) {
                // Find where the actual identifier starts (after keywords)
                if let Some(idx) = line.find(pattern) {
                    // Skip to the actual name after keywords
                    let name_start =
                        idx + pattern.len() - pattern.split_whitespace().last().unwrap_or("").len();
                    return Some((line_num as u32, name_start as u32));
                }
            }
        }
        None
    }
}

fn find_positions_in_file(path: &str) -> Result<FilePositions, std::io::Error> {
    let content = fs::read_to_string(path)?;
    Ok(FilePositions { content })
}
